# committeesList: https://raw.githubusercontent.com/unitedstates/congress-legislators/main/committees-current.yaml
committeesList: https://raw.githubusercontent.com/ericisaiah/congress-legislators/youtube-updates-august-2021/committees-current.yaml
